blank_pull_requests_enabled: false
contact_links:
  - name: LightSpeed WP Support
    url: https://lightspeedwp.agency
    about: For paid support inquiries, please contact us directly via our website.
    email: support@lightspeedwp.agency
