compliance:
  - GDPR
  - WCAG 2.1

data_sensitivity: public

project_type: wordpress-plugin

development_status: active

license: gpl-3.0

audience:
  - travel-agencies
  - tour-operators
  - developers

tech_stack:
  - PHP
  - WordPress
  - WooCommerce

version: 1.2.0

documentation_url: https://lsx.design/docs/tour-operator

support_url: https://lightspeedwp.agency/support

project_priority: core
