# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-ZA"
early_access: false
commands:
  enabled: true
linked_issues:
  enabled: true
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - '.*'
  path_instructions:
    - path: '**/*.{php,js,ts,jsx,tsx}'
      instructions: |
        - Follow WordPress coding standards.
        - Escape output and sanitize input.
        - Follow plugin security best practices.
        - Enforce prefixing for all functions, classes, and constants to avoid naming collisions.
        - Check for accessibility best practices in UI code (labels, ARIA attributes, color contrast).
        - Ensure inline documentation/comments for all custom functions and classes.
        - Ensure consistent formatting and schema validation.
        - Keep documentation up to date and clear.
        - On Pull Requests check for updates to the changelog file.
chat:
  auto_reply: true
