name: CI

on:
  pull_request:
  push:
    branches: ["2.1-trunk"]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:js
      - run: npm run lint:css
      - run: npm run build
      - name: Run Playwright tests
        run: |
          npx playwright install --with-deps
          npx playwright test
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer deps
        run: composer install --no-interaction --no-progress
      - name: PHP CodeSniffer (WPCS)
        run: vendor/bin/phpcs -q
