# .github/workflows/notify-slack.yml

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    # Add this line to check if the pull request actor is NOT Dependabot
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          payload: '{"text": ":new: New pull request created by ${{ github.actor }}"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
