name: Deploy to WordPress.org
on:
  # Trigger on push with tags
  push:
    tags:
    - "*"
  
  # Trigger manually from GitHub Actions UI
  workflow_dispatch:

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master

    # Step to fix the "dubious ownership" issue
    - name: Set safe directory for Git
      run: git config --global --add safe.directory /github/workspace

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: tour-operator
