name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
  workflow_dispatch:

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Install Subversion
      run: sudo apt-get update && sudo apt-get install -y subversion rsync git zip

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    # Step to fix the "dubious ownership" issue
    - name: Set safe directory for Git
      run: git config --global --add safe.directory /github/workspace

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: tour-operator
        TAG: ${{ github.ref_name }}
